### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/sonic-pi-taster-old#4]
- [ ] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [ ] hardware.yml
- [ ] software.yml
- [ ] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
This resource has been superseded by https://github.com/raspberrypilearning/getting-started-with-sonic-pi
